encoding: utf-8

# SEO相关信息
title: Burning Blog
description: Burning的个人博客
keywords: Burning,Blog,Python,C++,JavaScript
author: Burning
footerText: ''

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'cli.bat', 'dist.tar.gz']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: 'https://burning846.github.io'
baseurl: ''

# 吐个槽地址，会在chat页面中重定向到该地址
tucaoUrl: https://github.com/burning846/burning846.github.io/issues

# 菜单
menu:
  - title: 首页
    url: /
  - title: 归类
    url: /pages/categories.html
  - title: 搜索
    url: /pages/search.html
  - title: 友链
    url: /pages/links.html
  - title: 留言
    url: /pages/chat.html
  - title: 关于
    url: /pages/about.html

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: true

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 腾讯MTA移动分析,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extMTA: false

# 百度收录自动推送,不需要请设置为false
extBaidu: false

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: true

# 友情链接
links:
  - title: 文科中的技术宅
    url: https://www.townwang.com
  - title: Auuu Nya Blog
    url: http://mu1er.cn
  - title: 春风十里
    url: https://www.geek-era.com
  - title: 阿川的个人博客
    url: https://achuan.io
  - title: 魏文成博客
    url: https://www.wwc.ren
  - title: 06m
    url: https://www.06m.me
  - title: 达达知识
    url: https://www.dadapush.com/
  - title: 祈雨的博客
    url: https://wakzz.cn/
  - title: hongCYu’s Blog
    url: https://hongcyu.cn/
